//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xecrets.Words.RestApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xecrets.Words.RestApi.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;starting&quot;: {
        ///    &quot;aar&quot;: 1,
        ///    &quot;aba&quot;: 9,
        ///    &quot;abb&quot;: 7,
        ///    &quot;abd&quot;: 2,
        ///    &quot;abe&quot;: 5,
        ///    &quot;abh&quot;: 2,
        ///    &quot;abi&quot;: 4,
        ///    &quot;abj&quot;: 3,
        ///    &quot;abl&quot;: 5,
        ///    &quot;abn&quot;: 4,
        ///    &quot;abo&quot;: 13,
        ///    &quot;abr&quot;: 10,
        ///    &quot;abs&quot;: 28,
        ///    &quot;abu&quot;: 5,
        ///    &quot;aca&quot;: 3,
        ///    &quot;acc&quot;: 63,
        ///    &quot;ace&quot;: 2,
        ///    &quot;ach&quot;: 10,
        ///    &quot;aci&quot;: 2,
        ///    &quot;ack&quot;: 5,
        ///    &quot;acm&quot;: 1,
        ///    &quot;aco&quot;: 7,
        ///    &quot;acq&quot;: 9,
        ///    &quot;acr&quot;: 7,
        ///    &quot;act&quot;: 19,
        ///    &quot;acu&quot;: 4,
        ///    &quot;ada&quot;: 7,
        ///    &quot;add&quot;: 21,
        ///    &quot;ade&quot;: 6,
        ///    &quot;adh&quot;: 6,
        ///    &quot;adi&quot;: 4,
        ///    &quot;adj&quot;: 4,
        ///    &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string trigrams_en_json {
            get {
                return ResourceManager.GetString("trigrams_en_json", resourceCulture);
            }
        }
    }
}
