//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xecrets.Words.Cmd.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xecrets.Words.Cmd.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gösta Berlings saga. Skrifter av Selma Lagerlöf [1933]
        ///
        ///
        ///
        ///
        ///
        ///Bokutgåva
        ///
        ///
        ///Albert Bonniers förlag, Stockholm 1933. [Första upplagan utkom 1891]
        ///
        ///
        ///
        ///
        ///
        ///Epub-version
        ///
        ///
        ///
        ///
        ///Litteraturbanken
        ///
        ///
        ///
        ///
        ///
        ///Skapad 2023-10-16.
        ///
        ///
        ///
        ///
        ///
        ///Läs mer
        ///
        ///
        ///Här kan du läsa verket på Litteraturbanken. Mer om och av Selma Lagerlöf kan du läsa här.
        ///
        ///
        ///
        ///
        ///
        ///Litteraturbanken.se – The Swedish Literature Bank
        ///
        ///
        ///
        ///
        ///
        ///Karta över Lövsjö härad i Värmland.
        ///
        ///
        ///
        ///
        ///
        ///INLEDNING.
        ///
        ///
        ///I. Prästen.
        ///
        ///
        ///Äntligen stod prästen i predikstolen.
        ///
        ///Församlingens huvuden lyftes. Så, dä [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LagerlofS_GostaBerlingsSaga1933 {
            get {
                return ResourceManager.GetString("LagerlofS_GostaBerlingsSaga1933", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herr Arnes penningar
        ///
        ///
        ///
        ///
        ///
        ///Bokutgåva
        ///
        ///
        ///Iduns redaktion, Stockholm 1903.
        ///
        ///
        ///
        ///
        ///
        ///Epub-version
        ///
        ///
        ///
        ///
        ///Litteraturbanken
        ///
        ///
        ///
        ///
        ///
        ///Skapad 2024-02-26.
        ///
        ///
        ///
        ///
        ///
        ///Läs mer
        ///
        ///
        ///Här kan du läsa verket på Litteraturbanken. Mer om och av Selma Lagerlöf kan du läsa här.
        ///
        ///
        ///
        ///
        ///
        ///Litteraturbanken.se – The Swedish Literature Bank
        ///
        ///
        ///
        ///
        ///
        ///I Solberga prästgård.
        ///
        ///
        ///I.
        ///
        ///
        ///På den tiden, då kung Fredrik den andre af Danmark regerade öfver Bohuslän, bodde i Marstrand en fattig fiskmånglare, som hette Torarin. Han var en så svag och ringa man, hans ena arm  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LagerlofS_HerrArnesPenningar {
            get {
                return ResourceManager.GetString("LagerlofS_HerrArnesPenningar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerusalem. I. I Dalarne. Berättelse
        ///
        ///
        ///
        ///
        ///
        ///Bokutgåva
        ///
        ///
        ///Albert Bonniers förlag, Stockholm 1901.
        ///
        ///
        ///
        ///
        ///
        ///Epub-version
        ///
        ///
        ///
        ///
        ///Litteraturbanken
        ///
        ///
        ///
        ///
        ///
        ///Skapad 2023-06-04.
        ///
        ///
        ///
        ///
        ///
        ///Läs mer
        ///
        ///
        ///Här kan du läsa verket på Litteraturbanken. Mer om och av Selma Lagerlöf kan du läsa här.
        ///
        ///
        ///
        ///
        ///
        ///Litteraturbanken.se – The Swedish Literature Bank
        ///
        ///
        ///
        ///
        ///
        ///Sjätte tusendet.
        ///
        ///
        ///
        ///TILL
        ///
        ///SOPHIE ELKAN
        ///
        ///MIN KAMRAT
        ///
        ///I LIF OCH DIKTNING
        ///
        ///
        ///
        ///
        ///
        ///INLEDNING.
        ///
        ///
        ///
        ///
        ///
        ///Ingmarssönerna.
        ///
        ///
        ///________
        ///
        ///
        ///
        ///
        ///
        ///I.
        ///
        ///
        ///Det var en ung karl, som gick och plöjde sitt träde en sommarm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LagerlofS_JerusalemI {
            get {
                return ResourceManager.GetString("LagerlofS_JerusalemI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victor Hugo
        ///
        ///LES MISÉRABLES
        ///
        ///Tome I--FANTINE
        ///
        ///(1862)
        ///
        ///
        ///TABLE DES MATIÈRES
        ///
        ///Livre premier--Un juste
        ///
        ///Chapitre I Monsieur Myriel
        ///Chapitre II Monsieur Myriel devient monseigneur Bienvenu
        ///Chapitre III À bon évêque dur évêché
        ///Chapitre IV Les oeuvres semblables aux paroles
        ///Chapitre V Que monseigneur Bienvenu faisait durer trop longtemps ses
        ///     soutanes
        ///Chapitre VI Par qui il faisait garder sa maison
        ///Chapitre VII Cravatte
        ///Chapitre VIII Philosophie après boire
        ///Chapitre IX Le frère raconté pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pg17489 {
            get {
                return ResourceManager.GetString("pg17489", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El ingenioso hidalgo don Quijote de la Mancha
        ///
        ///
        ///
        ///por Miguel de Cervantes Saavedra
        ///
        ///
        ///
        ///
        ///
        ///El ingenioso hidalgo don Quijote de la Mancha
        ///
        ///
        ///  
        ///Tasa
        ///
        ///  
        ///Testimonio de las erratas
        ///
        ///  
        ///El Rey
        ///
        ///  
        ///Al Duque de Béjar
        ///
        ///  
        ///Prólogo
        ///
        ///  
        ///Al libro de don Quijote de la Mancha
        ///
        ///
        ///
        ///Que trata de la condición y ejercicio del famoso
        ///hidalgo don Quijote de la Mancha
        ///
        ///Que trata de la primera salida que de su tierra hizo
        ///el ingenioso don Quijote
        ///
        ///Donde se cuenta la graciosa manera que tuvo don
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pg2000 {
            get {
                return ResourceManager.GetString("pg2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Project Gutenberg eBook of Ulysses
        ///    
        ///This ebook is for the use of anyone anywhere in the United States and
        ///most other parts of the world at no cost and with almost no restrictions
        ///whatsoever. You may copy it, give it away or re-use it under the terms
        ///of the Project Gutenberg License included with this ebook or online
        ///at www.gutenberg.org. If you are not located in the United States,
        ///you will have to check the laws of the country where you are located
        ///before using this eBook.
        ///
        ///Title: Ulysses [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pg4300 {
            get {
                return ResourceManager.GetString("pg4300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                          NOTE DEL TRASCRITTORE
        ///
        ///—Corretti gli ovvii errori tipografici e di punteggiatura.
        ///
        ///—L’indice non è presente nell’opera originale; ne è stato prodotto ed
        /// aggiunto uno a cura del trascrittore.
        ///
        ///
        ///
        ///
        ///                            SIBILLA ALERAMO
        ///
        ///                               UNA DONNA
        ///
        ///                                ROMANZO
        ///
        ///                     Terza edizione-25.º Migliaio
        ///
        ///[Illustration: LOGO]
        ///
        ///                                FIRENZE
        ///                     R. BEMPO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pg47786 {
            get {
                return ResourceManager.GetString("pg47786", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                            Novelle Napolitane
        ///
        ///
        ///                                   DI
        ///
        ///                          SALVATORE DI GIACOMO
        ///
        ///
        ///                    _Prefazione di BENEDETTO CROCE._
        ///
        ///
        ///
        ///                                 MILANO
        ///                        FRATELLI TREVES, EDITORI
        ///                            Quarto migliaio.
        ///
        ///
        ///
        ///
        ///                         PROPRIETÀ LETTERARIA.
        ///
        ///       _I diritti di riproduzione e di traduzione sono riservati
        ///    per tutti i paesi, compresi la Svezia, la N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pg57040 {
            get {
                return ResourceManager.GetString("pg57040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                               Thomas Mann
        ///
        ///                            Gesammelte Werke
        ///
        ///
        ///                                  1924
        ///                      S. Fischer / Verlag / Berlin
        ///
        ///                              Thomas Mann
        ///
        ///
        ///
        ///
        ///                             Der Zauberberg
        ///
        ///
        ///                                 Roman
        ///
        ///                              Erster Band
        ///
        ///
        ///                                  1924
        ///                      S. Fischer / Verlag / Berlin
        ///
        ///
        ///                        Erste bis zehn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pg65661 {
            get {
                return ResourceManager.GetString("pg65661", resourceCulture);
            }
        }
    }
}
